version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8085:80" # Expose port 8080 on the host
    volumes:
      - .:/var/www/html # Sync your project files with the container
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB's default port
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
